version: '3'
services:
  opa:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/workspace:cached
    environment:
      ENDPOINT_URL: http://dynamodb:8000/
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
    links:
      - dynamodb:dynamodb
    command: tail -f /dev/null
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb
    ports:
      - 8000:8000
